weights: yolov5m.pt
cfg: ''
data: data/handbag.yaml
hyp: data/hyp.scratch.yaml
epochs: 1000
batch_size: 8
img_size:
- 960
- 960
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 4
total_batch_size: 8
world_size: 1
global_rank: -1
