weights: ./runs\exp31\weights_backup_epoch103\last.pt
cfg: ''
data: data/handbag.yaml
hyp: data/hyp.scratch.yaml
epochs: 200
batch_size: 8
img_size:
- 1080
- 1080
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 4
total_batch_size: 8
world_size: 1
global_rank: -1
